cd SQL/sqlcl/bin/
./sql 'SINGH24_ADITYAKUM_SCHEMA_R6LGN/"$Gz8ZWRYTS263NW2HRQ02UITT5XLTQ"@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCPS)(HOST=db.freesql.com)(PORT=2484))(CONNECT_DATA=(SERVICE_NAME=23ai_34ui2)))'
